# Generated by Django 2.2.5 on 2019-09-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0002_auto_20190919_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='info',
            field=models.CharField(default=12, max_length=40),
            preserve_default=False,
        ),
    ]
